#DOMANIN REFERENCES
domain: "https://trash.ninja"
baseurl: "/"
url: "https://trash.ninja"

#TITLES AND REFERNCES
title: Trash.Ninja
email: email@email.com
description: >- # this means to ignore newlines until
  An esoteric collection of musings, art, projects and scribbles created
  by a lone idiot.

#LOGO FILE
logo: logo-grey-thin.png

# BUILD SETTINGS
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

# THEME SPECIFIC
style: ocean
listen_for_clients_preferred_style: true
header_pages:
  - index.md
  - about.md
footer: 'find me on <a href="https://fosstodon.org/web/@OrchidMantis9">Mastodon</a>'
