#DOMANIN REFERENCES
domain: "https://trash.ninja"
baseurl: "/"
url: "https://trash.ninja"

#TITLES AND REFERNCES
title: Trash.Ninja
name: Trash.Ninja
email: email@email.com
description: >- # this means to ignore newlines until
  An esoteric collection of musings, art, projects and scribbles created
  by a lone idiot.

#LOGO FILE
logo: logo-moai.png

# BUILD SETTINGS
remote_theme: b2a3e8/jekyll-theme-console
permalink: /:categories/:title/
plugins:
  - jekyll-feed

# THEME SPECIFIC
style: ternative
listen_for_clients_preferred_style: true
header_pages:
  - index.md
  - categories.md
  - about.md
footer: 'OM9 🗿 find me on <a rel="me" href="https://fosstodon.org/web/@OrchidMantis9">Mastodon</a>'
rss: 'rss'